### ISSUE TITLE
Technical debt after the Chromium 61 upgrade

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#10836]
_List of hacks and workarounds made during the upgrade to Chromium 61._
_We should probably fix them before Chromium 61 is merged or right after._

/cc @zcbenz, @tonyganch, @gavignus, @alespergl, @deepak1556, @MarshallOfSound 

#### Probably should be fixed before the release
- [x] [electron] #11244 Fix "\<webview> tag found-in-page event emits when a request is made" test
- [x] [electron] #11245 Fix "nativeImage module addRepresentation() ..." tests
- [x] [electron] #11246 Fix "crashReporter module" tests
- [x] [electron] #11243 Assertion failed: (err == 0), function uv_loop_delete, file ../../vendor/node/deps/uv/src/uv-common.c, line 661.
- [x] [docs] #11242 Remove async menu from the docs
_____

#### Probably can be safely postponed
- [ ] [libcc] electron/libchromiumcontent#399 New patch: Checking pointer returned from browser plug-in. Ignoring nullptr values which would cause BAD ACCESS errors
- [ ] [electron] #10754 Fix "onbeforeunload" tests
- [x] [electron] #10776 Deprecate and remove "corsEnabled" option from "webFrame.registerURLSchemeAsPrivileged"
- [x] [electron] #10780 Fix GTK deprecation warnings
- [x] [electron] #11248 FIXME: Use `sk_tool_utils::copy_to()` instead of `.deepCopyTo()`.
- [x] [libcc] electron/libchromiumcontent#400 Use custom libc++?
- [ ] [node] electron/node#26 FIXME: Use redefined version of the `internalModuleStat` function
- [x] [node] electron/node#25 UPSTREAM: Include node_platform.h instead of forward declaration
- [ ] [electron] #11294 Fix an alpha type of a bitmap returned by `gfx::JPEGCodec::Decode()`

**Comment by ibash** [comment]
#11243 is merged - release the beta! :)

**Comment by CapOM** [comment]
An update on this ?

**Comment by nornagon** [comment]
@CapOM are you looking for any specific info? most of the items listed have been completed.

**Comment by CapOM** [comment]
I get some crashes with nativeImage.createFromPath when it has `Template` in its name after upgrading electron (see https://electronjs.org/docs/api/native-image#template-image) so I was wondering if something was still pending.

**Comment by nornagon** [comment]
Please open a new bug for the issue you're seeing, I think this one has cobwebs on it :)
