### ISSUE TITLE
Tracking issue: //extensions integration

### ISSUE THREAD

**Issue by nornagon** [electron/electron#19447]
This is a tracking issue for the work remaining to migrate our Chrome Extensions support away from our ad-hoc polyfills to the official //extensions code in Chromium.

- [x] Preliminary support behind a feature flag https://github.com/electron/electron/pull/17440
- [ ] Sketch out complete API
  - Should include:
    - Loading and unloading extensions
    - Callbacks for relevant events
    - Exposing relevant info, e.g. badging, notifications, other requests from extensions that the main process might want or need to intervene in
- [x] Load extensions on the IO thread instead of the main thread
- [x] Support for background pages #21591
- [x] Support for devtools extensions #19515 #21779
- [x] API Documentation #21809
- [x] Deprecate polyfill-based extensions support #21812
- [x] Enable feature flag by default #21814
- [x] Remove old extensions code #23340
- [ ] Finalize API
- [ ] Assess all TODOs

**Comment by nornagon** [comment]
Building on the API that @samuelmaddock suggested in #17440, here's a draft to be evolved as requirements become evident.

```ts
interface Extension {
  id: string,
  path: string,
  manifest: chrome.Manifest
}

class Session {
  /** Emitted when extension is installed and ready. */
  on(event: 'extension-ready', listener: (event: Event, extension: Extension) => void): this;

  loadExtension(path: string): Extension;
  removeExtension(extensionId: string): void;
  enableExtension(extensionId: string): void;
  disableExtension(extensionId: string): void;

  getExtension(extensionId: string): Extension;
}
```

**Comment by nornagon** [comment]
To remove in the new world:
- `BrowserWindow.addDevToolsExtension`
- `BrowserWindow.removeDevToolsExtension`
- `BrowserWindow.getDevToolsExtensions`

//extensions doesn't distinguish between devtools extensions and non-devtools extensions. We can deprecate these functions and delegate them to `defaultSession.loadExtension` &c. to avoid breaking users without warning.

**Comment by sentialx** [comment]
@nornagon How `chrome.tabs` related functions will be handled? Could I listen for example to `chrome.tabs.create`? I suggest adding for example a `extensions-tabs-create` event which is fired when an extension calls a `chrome.tabs.create` function to the `Session` class.

**Comment by nornagon** [comment]
A lot of the `chrome.tabs` APIs don't make a lot of sense in an Electron context (e.g. ` chrome.tabs.getAllInWindow`), so I don't think it makes sense for us to implement the full API. In general we aren't aiming to support every Chrome extension, only just enough to support the most common use cases (in particular, devtools extensions like React Devtools, and the internal PDF viewer extension). We probably want to make sure it's possible for apps to add custom implementations for APIs we don't support, e.g. through preload scripts.

Do you have a particular use-case in mind for the `chrome.tabs.create` API?

**Comment by sentialx** [comment]
I'm making a web browser with multi-window and tabs support, so it would be nice to at least extend the `chrome` apis in background and content scripts.

**Comment by sentialx** [comment]
@nornagon What bothers me now is how injecting preload scripts into the background pages would work? Will be there a `session.setBackgroundPreloads` API or something? Also, content scripts execute in isolated worlds, so how would I know in which world there's a `chrome` object?

**Comment by nornagon** [comment]
Yes, it should be possible to inject preload scripts into background pages. [session.setPreloads](https://electronjs.org/docs/api/session#sessetpreloadspreloads) should do it. I think the easiest way to extend our current preload API would be to add a way for a preload script to know what kind of world it's being injected into (e.g. a `global.electron.worldType` variable or similar). Ideally we'd extend the preload API so you could specify a different script for each world type.

**Comment by kinop112365362** [comment]
Is there a guide to participating in the contributing code, about Google's extensions? @nornagon

**Comment by MarshallOfSound** [comment]
What happens if you load the same extension id with a different version, does it replace the old one, or fail, or something else ❓

**Comment by sentialx** [comment]
Is there a list of supported `chrome` APIs in the new extensions implementation?

**Comment by nornagon** [comment]
Not yet but there should be! So far I think the list is something like:

- `chrome.runtime.*`
- `chrome.extension.getURL` (and maybe a couple of other `chrome.extension` APIs?)
- `chrome.tabs.executeScript` - limited support, requires specifying tabId
- `chrome.tabs.sendMessage`
- `chrome.devtools.*` for devtools extensions
- `chrome.storage.local.*`

this is just off the top of my head though, I think that there are quite a few more that may be supported already (e.g. i think most of the things [in this list](https://source.chromium.org/chromium/chromium/src/+/master:extensions/common/api/_api_features.json;l=1?q=_api_fea&sq=&ss=chromium&originalUrl=https:%2F%2Fcs.chromium.org%2F) should work?) and there may be some restrictions on some of these APIs that I don't recall. I'll do a more thorough investigation soon and add this list to the docs at some point.

Ultimately though, we are not interested in maintaining anything close to feature parity with Chrome extensions. Our goal is to support devtools extensions (which we already do to some extent, so this will be maintaining roughly the same level of support) and to enable internal extensions like the PDF viewer. There are many concepts in Chrome's extensions API which do not map well to Electron—things like tabs, windows, the omnibox, sync profiles and so on—and it would be far too much effort to hook and expose all of these to app authors.

**Comment by sentialx** [comment]
@nornagon Thanks for your great and hard work on it! I would be very grateful if `chrome.extension.getBackgroundPage` and `chrome.extension.getViews` would be also supported since it's very hard to actually implement this in JS by using only IPC. Or I would also appreciate if you could at least guide me how these APIs could be implemented.

**Comment by nornagon** [comment]
those seem plausibly doable! i'll look into it.

**Comment by spike-the-coder** [comment]
Super excited about this!

**Comment by samuelmaddock** [comment]
cc @sentialx @alexstrat @stewartlord @Thomas101

There are potentially breaking changes being introduced with the planned deprecation of Electron's current extension support in #21812. Projects adding additional Chrome APIs using the existing extensions implementation would likely cease to function.

I alerted @nornagon to this problem and he mentioned investigating whether it would be possible to support both implementations.

As far as I know, @nornagon is the only contributor actively working on the new extensions system implementation. Based on his work in #21779, it would likely be a considerable effort to support all Chrome APIs. I would encourage folks with an interest in this to start investigating solutions using the new extensions system.

**Comment by stewartlord** [comment]
@samuelmaddock Thanks for the heads up! I'm excited to see this work continue to move forward. It would be great to preserve compatibility for a couple of releases until the new extension system is able to support existing implementations and apps in the wild have a chance to switch over.

Are you expecting BC breakage in 8.0?

**Comment by nornagon** [comment]
There are no changes to extensions scheduled for 8.0, currently I'm targeting 9.0 for the switchover, so that gives us a bit of breathing room.

**Comment by stewartlord** [comment]
Thanks @nornagon. Thrilled that you are working on it btw! Do you know what APIs will be affected and when we can start testing early builds? Extension support in our app is largely independent of the support that is bundled with Electron, but there are a couple of key touch points like `InspectorFrontendAPI.addExtensions()`

**Comment by nornagon** [comment]
here's what's currently available in the background page:

<img width="552" alt="DevTools_-_chrome-extension___dedfniognklmebaammilhkengncchdbb__generated_background_page_html" src="https://user-images.githubusercontent.com/172800/73011909-14361c00-3dca-11ea-970c-bb51d9924c71.png">

and in content scripts:

<img width="520" alt="Developer_Tools_-_https___slack_com_" src="https://user-images.githubusercontent.com/172800/73011995-39c32580-3dca-11ea-8048-007c71074ac0.png">

**Comment by nornagon** [comment]
I think devtools extensions stuff is handled a bit differently; it's injected by the devtools frontend itself and I think we should automatically be supporting the full `chrome.devtools` API.

**Comment by nornagon** [comment]
FYI, #21814 has been merged, and tomorrow's nightly build should have the new extensions stuff for you to try out!

**Comment by nornagon** [comment]
Here's a list of the supported APIs. Some of these might still be a little shaky; I'm working on adding tests for all these. https://github.com/electron/electron/pull/22021

**Comment by sentialx** [comment]
@nornagon Would be great if there would be support for `chrome.webRequest` API, since it's also very tricky to implement in plain JS, because the Electron's `webRequest` module doesn't allow registering multiple handlers (https://github.com/electron/electron/issues/18301).

Also, how can we inject custom `chrome` APIs into the correct isolated world as discussed [here](https://github.com/electron/electron/issues/19447#issuecomment-516091237)?

**Comment by samuelmaddock** [comment]
I tested v9.0.0-beta.1 with these changes. There are actually a few more APIs available than reported. To add the rest, more permissions needed to be added to the extension manifest.

Here's a full list pulled from https://developer.chrome.com/extensions/declare_permissions
```
"permissions": ["activeTab", "alarms", "background", "bookmarks", "browsingData", "certificateProvider", "clipboardRead", "clipboardWrite", "contentSettings", "contextMenus", "cookies", "debugger", "declarativeContent", "declarativeNetRequest", "declarativeWebRequest", "desktopCapture", "displaySource", "dns", "documentScan", "downloads", "enterprise.deviceAttributes", "enterprise.hardwarePlatform", "enterprise.platformKeys", "experimental", "fileBrowserHandler", "fileSystemProvider", "fontSettings", "gcm", "geolocation", "history", "identity", "idle", "idltest", "management", "nativeMessaging", "networking.config", "notifications", "pageCapture", "platformKeys", "power", "printerProvider", "privacy", "processes", "proxy", "sessions", "signedInDevices", "storage", "system.cpu", "system.display", "system.memory", "system.storage", "tabCapture", "tabs", "topSites", "tts", "ttsEngine", "unlimitedStorage", "vpnProvider", "wallpaper", "webNavigation", "webRequest", "webRequestBlocking", "<all_urls>"]
```

I've enumerated them all into a JSON interface-like object here
https://gist.github.com/samuelmaddock/5413a55d5bbc037cf42a217257b70a02

![chrome_2020-02-12_19-00-20zGwW](https://user-images.githubusercontent.com/1656324/74388658-edb44100-4dc9-11ea-896a-ea40dfad412c.png)

It's worth noting these APIs might not be functional even if they're available. I suspect `webRequest` will need more work.

**Comment by samuelmaddock** [comment]
Loading an extension with all permissions requested will log warnings about missing features. This is to be expected unless implemented by a contributor.

Missing manifest key parsers:
- browser_action
- short_name

Missing APIs:
- activeTab
- background
- bookmarks
- browsingData
- certificateProvider
- contentSettings
- contextMenus
- cookies
- debugger
- declarativeContent
- desktopCapture
- downloads
- enterprise
- experimental
- fileBrowserHandler
- fileSystemProvider
- fontSettings
- gcm
- geolocation
- history
- identity
- idltest
- management
- notifications
- pageCapture
- platformKeys
- privacy
- processes
- proxy
- sessions
- signedInDevices
- tabCapture
- tabs
- topSites
- tts
- ttsEngine
- wallpaper
- webNavigation

And here's something I noticed while testing:
- `sender.tab.url` is missing in `chrome.runtime.onMessage` callback

**Comment by sentialx** [comment]
@samuelmaddock How do you open devtools for extension's background `webContents`?

**Comment by samuelmaddock** [comment]
> 
> 
> @samuelmaddock How do you open devtools for extension's background `webContents`?

Add this to your browser script
```js
app.commandLine.appendSwitch('remote-debugging-port', '9222')
```

Then open `chrome://inspect` in Chrome to remotely debug the background page. Thanks to @nornagon for figuring this out.

**Comment by sentialx** [comment]
I would suggest adding `webContents` property or `openDevTools` method to the `Extension` object returned by `session.loadExtension`.

**Comment by sentialx** [comment]
I've tried adding my own `chrome` APIs by using preload script. Injecting APIs that don't have their own property in `chrome` object such as `browserAction`, works. However, the partially implemented APIs such as `chrome.tabs` are later replacing those APIs that I've injected.

Example preload script:
```typescript
window.chrome = {
  tabs: {
    get: () => {}
  },
  browserAction: {
    ...
  }.
}
```

I'm assigning the `chrome` object, since it doesn't exist yet. Later the `chrome.tabs` API gets replaced by the native implementation.

I tried also assigning the `window.chrome` object on `process.loaded` event, but it also didn't work.

![image](https://user-images.githubusercontent.com/11065386/74475874-90db8800-4ea8-11ea-8786-2b9aa9c0b1c7.png)

**Comment by sentialx** [comment]
Nevermind, adding my `chrome.tabs` APIs in `process` `document-start` event worked fine.

**Comment by sentialx** [comment]
Currently, I'm stuck with injecting my Chrome APIs into the `content_scripts` since they work in isolated worlds. We should have more control on how the native Chrome APIs are injected. Also, I'm trying to implement popup pages, but the `chrome` API is in an isolated world rather than in a main world and the other extensions shouldn't load their `content_scripts` into the popup page.

**Comment by samuelmaddock** [comment]
> Also, I'm trying to implement popup pages, but the `chrome` API is in an isolated world rather than in a main world and the other extensions shouldn't load their `content_scripts` into the popup page.

I think what's needed is for a new `popup` type to be added to `WebContents` so that content scripts can be excluded.
https://www.electronjs.org/docs/api/web-contents#contentsgettype

Also, I don't think the new background pages use the `backgroundPage` type yet.

**Comment by sentialx** [comment]
Yeah, I noticed that the background pages have `remote` type and don't have `session` property in IPC messages (`e.sender.session` is undefined).

**Comment by samuelmaddock** [comment]
@sentialx Have you been able to try using https://github.com/sentialx/electron-extensions side-by-side with the new native extensions implementation? Would the new changes break this library?

**Comment by sentialx** [comment]
@samuelmaddock I had to change the protocol from `chrome-extension` to some other for example `electron-extension`, but overall it works perfectly.

**Comment by sentialx** [comment]
So what's blocking me from moving to the native implementation is:
- no `chrome.tabs.connect` - there is no way to implement this using JS other than rewriting whole communication to JS (`chrome.tabs.sendMessage`, `chrome.runtime.onMessage`, `chrome.runtime.connect`, `chrome.runtime.Port` etc.)
- no way to inject custom `chrome` APIs to `content_scripts` and popups.

What would be nice to have:
- `chrome.webRequest` - as I said before it's really tricky to implement it in JS using Electron's `webRequest` module. However, not impossible.
- `chrome.webNavigation.getAllFrames`, `chrome.webNavigation.getFrame`

Sorry if I'm requesting too much. I tried to make a PR, but I had problems with building Electron and I don't know where to start basically.

As I read Chromium's source code, I think there's nothing left to copy to Electron regarding `chrome.tabs.connect`. Would it be sufficient to just include the API in this file? Perhaps I'm missing something, I don't believe that it would be this easy. https://github.com/electron/electron/blob/ced487467c0221c6ec30ddc1c42620b8ad047d82/shell/common/extensions/api/tabs.json#L121

**Comment by samuelmaddock** [comment]
> Sorry if I'm requesting too much. I tried to make a PR, but I had problems with building Electron and I don't know where to start basically.

The easiest way to get setup is by using the electron utility [build-tools](https://github.com/electron/build-tools). Instructions for installing are in the readme.

> no way to inject custom `chrome` APIs to `content_scripts` and popups.

I might be able to implement a solution for this. Which Chrome APIs are still missing in content scripts though?

> `chrome.webRequest` - as I said before it's really tricky to implement it in JS using Electron's `webRequest` module. However, not impossible.

With native extensions, [declaring permissions](https://developer.chrome.com/extensions/declare_permissions) is now required. Declaring the "webRequest" permission should grant access to this API.

**Comment by sentialx** [comment]
> Which Chrome APIs are still missing in content scripts though?
I was about to say `chrome.tabs` but you reminded me that `content_scripts` only need some of the `chrome` APIs. So there is no need to inject my own APIs and there only remains support for `popups`. Is `chrome.i18n` implemented though?

**Comment by samuelmaddock** [comment]
> Is `chrome.i18n` implemented though?

It doesn't look like it is. I'll look into implementing this natively.

**Comment by samuelmaddock** [comment]
> As I read Chromium's source code, I think there's nothing left to copy to Electron regarding chrome.tabs.connect. Would it be sufficient to just include the API in this file? Perhaps I'm missing something, I don't believe that it would be this easy. 

It was that easy, thanks to @nornagon's initial work in integrating the `tabs` API. 😄 #22457

**Comment by sentialx** [comment]
I made a PR ~adding~ trying to add `chrome.cookies` API, but there are `browser/ui` references and many errors.

**Comment by samuelmaddock** [comment]
I'll be looking into adding popup support soon. The work in #22217 will help in assigning a new `WebContent` type for them.

A new Electron API will be needed to create an [`ExtensionHost`](https://source.chromium.org/chromium/chromium/src/+/master:extensions/browser/extension_host.h) instance for popups. I'm hoping we can leverage a `BrowserView` for displaying the popup web contents. The drawback would be that a `BrowserView` can't be rendered outside of the window, but would offer a similar UI without needing to write a new UI view.

**Comment by sentialx** [comment]
@samuelmaddock Currently, with my own extensions implementation, I host a <webview> inside a `BrowserView` with some drop shadow etc.

**Comment by samuelmaddock** [comment]
@sentialx Loading an extension page within any `WebContents` seems to load `chrome.*` extension bindings. Here's an example loaded into a `BrowserView`:

```js
const extension = await session.defaultSession.loadExtension(
  path.join(__dirname, 'extension')
)
const win = new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: {
    nodeIntegration: false
  }
})
win.loadURL(`about:blank`)

const popupView = new BrowserView()
win.addBrowserView(popupView)
popupView.setBounds({ x: 0, y: 0, width: 256, height: 256 })
popupView.webContents.loadURL(`chrome-extension://${extension.id}/popup.html`)
popupView.webContents.openDevTools({ mode: 'detach', activate: true })
popupView.setBackgroundColor('#ff0000')
```

![Code_2020-03-06_20-02-43GMC7](https://user-images.githubusercontent.com/1656324/76133343-b52d0f00-5fe5-11ea-8075-1fba86c8c83d.png)

Is using a `<webview>` required for you? Seems like it should work without it.

**Comment by sentialx** [comment]
I don't think there is another way to achieve these animations. Thanks for your info though. Seems really nice :) I will check that.

![New-tab-Wexond-2020-03-07-11-17-18](https://user-images.githubusercontent.com/11065386/76141510-64f59180-6065-11ea-8e70-e9cc18ff4286.gif)

**Comment by sentialx** [comment]
Ok, great! I can confirm it's working! Thanks @samuelmaddock

**Comment by sentialx** [comment]
Update: attempting to load 1PasswordX crashes Electron:
```
 (node:10904) ExtensionLoadWarning: Warnings loading extension at C:\Users\Senti\AppData\Roaming\wexond\extensions\hdokiejnpimakedhajhdlcegeplioahd: Unrecognized manifest key 'author'. Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'minimum_chrome_version'. Unrecognized manifest key 'omnibox'. Unrecognized manifest key 'optional_permissions'. Unrecognized manifest key 'short_name'. Unrecognized manifest key 'update_url'. Permission 'tabs' is unknown or URL pattern is malformed. Permission 'notifications' is unknown or URL pattern is malformed. Permission 'contextMenus' is unknown or URL pattern is malformed. Permission 'webNavigation' is unknown or URL pattern is malformed. Invalid scheme for 'permissions[chrome://favicon/*]'. Permission 'cookies' is unknown or URL pattern is malformed. Permission 'privacy' is unknown or URL pattern is malformed. Permission 'history' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 3221225477
[1] npm ERR! wexond@4.0.0-nightly.31 start: `electron .`
[1] npm ERR! Exit status 3221225477
[1] npm ERR!
npm ERR! Failed at the wexond@4.0.0-nightly.31 start script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     C:\Users\Senti\AppData\Roaming\npm-cache\_logs\2020-03-07T11_00_33_173Z-debug.log
```

Also, how can I prevent `content_scripts` from injecting to certain URLs? (in my example `wexond://*`)

**Comment by sentialx** [comment]
`chrome.webRequest` API just doesn't work. Tried using this:

```
"permissions": ["webRequest", "webRequestBlocking", "<all_urls>"],
```

```javascript
chrome.webRequest.onBeforeRequest.addListener(
  (details) => {
    console.log(details)
    return { cancel: false };
  },
  { urls: ["<all_urls>"] },
  ["blocking"]
);
```

**Comment by samuelmaddock** [comment]
> Update: attempting to load 1PasswordX crashes Electron:

I've found this to happen when not loading a directory containing a `manifest.json` file. If there's a version subdirectory within `extensions\aeblfdkhhhdcdjpifhhbdiojplfjncoa`, try loading that directly.

> Also, how can I prevent `content_scripts` from injecting to certain URLs? (in my example `wexond://*`)

I don't think it has been considered yet and might need changes to allow filtering. We'll likely run into more questions like this since we're among the first trying out the new extensions system.

> chrome.webRequest API just doesn't work.

I tried this last night and noticed the same. There must not be the necessary hooks setup for this API to work yet.

**Comment by sentialx** [comment]
> There must not be the necessary hooks setup for this API to work yet.

I noticed that the `web_request.json` file missing. Maybe that's the problem?

**Comment by samuelmaddock** [comment]
> I noticed that the `web_request.json` file is missing. Maybe that's the problem?

The base `//extensions` implementation provides some APIs out of the box, [`web_request.json`](https://source.chromium.org/chromium/chromium/src/+/master:extensions/common/api/web_request.json) is one of those. We'll need to search through the chromium codebase to see how it's interacting with the `webRequest` API, then do the same in electron.

**Comment by sentialx** [comment]
> I've found this to happen when not loading a directory containing a manifest.json file. If there's a version subdirectory within extensions\aeblfdkhhhdcdjpifhhbdiojplfjncoa, try loading that directly.

Unfortunately, there's a problem with their `background.js` causing Electron to crash. When I removed the file from manifest.json, it worked. I can't tell what's wrong with the file since it's uglified and big.

**Comment by sentialx** [comment]
Sometimes I get an error related to the messaging:
```
Unchecked runtime.lastError: The message port closed before a response was received.
```
For example in the Tampermonkey popup page, which also doesn't really display. The scripts load but nothing adds to the popup's `<body>`.

![image](https://user-images.githubusercontent.com/11065386/76152326-afefc300-60be-11ea-818e-6b7675d8a87e.png)

**Comment by mitermayer** [comment]
What are the remaining blockers for this issue? Would love to contribute in any way to help push this along

**Comment by samuelmaddock** [comment]
@mitermayer this work is available in v9.x.y. Basic unpacked extensions can be loaded into a session. However, not all extension APIs are available or function properly. @sentialx and I have been contributing recently to fix some of  these issues.

Since Electron applications aren't constrained to the same tabbed browser model as traditional web browsers, some APIs such as `chrome.tabs` are intentionally left incomplete.

There are a few projects made to fill this gap:
- @sentialx maintains https://github.com/sentialx/electron-extensions which adds most APIs. I believe it's currently being worked on to make use of the new electron extensions feature.
- I created https://github.com/samuelmaddock/electron-browser-shell as a way to test development of electron extensions and add some missing APIs.

If you're looking to use any extension in the Chrome webstore, there's still much work to be done.

**Comment by sentialx** [comment]
@mitermayer 
I don't know the "stable blockers", but for me and probably for anyone who wants to support Chrome extensions in their app is:
- no `session` property in the `e.sender` object received through an ipc message, it makes it impossible to identify the session when messaging
- crash when loading for example 1Password X and probably many others
- no way to add additional properties to Tab object like `selected` or `highlighted`.
The rest can be implemented easily in JS.

**Comment by nornagon** [comment]
To clarify, it is not the intention of the Electron team to support loading arbitrary extensions from the Chrome Web Store. Our main goals with this effort are to:

1. Reduce our maintenance burden by aligning with Chrome's architecture,
2. Maintain & improve support for devtools extensions, and
3. Provide a more solid base on which app developers can build.

I think we still have some work to go with (3), but since supporting non-devtools extensions is a new feature, a few rough edges there aren't a stable blocker for us.

**Comment by sentialx** [comment]
Another thing that makes it difficult are CORS errors when extensions are trying to do an XHR request.
![image](https://user-images.githubusercontent.com/11065386/80278729-ef1eb580-86f8-11ea-9df4-875c2bfb0c01.png)

I made a temporary workaround [here](https://github.com/sentialx/electron-extensions/blob/master/src/browser/web-request-electron.ts).

**Comment by holmberd** [comment]
Any ideas for how one would map a specific background-page with the session the extension was loaded into?

For a content-script the context runs in the same session as the extensions were loaded into. A background-page on the other hand runs in a context of type `remote`, and therefore gets assigned a temporary session.

This makes it difficult to map which session the background-page should e.g. create a tab in, when extensions are loaded into multiple session.

**Comment by GoldSmyth** [comment]
Hi, I'm trying to find a way to activate the 'chrome.runtime' within the browser, currently the chrome object is empty. 

What is the easiest way to do this?

Also is it possible to import the cryptoTokenExtension that is available in Chrome into electron?

**Comment by sentialx** [comment]
@GoldSmyth You can download the extension from here: https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/resources/cryptotoken/manifest.json?q=cryptotokenextension

**Comment by GoldSmyth** [comment]
> @GoldSmyth You can download the extension from here: https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/resources/cryptotoken/

Thank you, this solved the issue I was having!

**Comment by corysimmons** [comment]
Bump or version to rollback to?

**Comment by nornagon** [comment]
I'm closing this as extensions support has landed and seems to be working fairly well, and as such there's not much use for a general-purpose tracking issue any more.
