### ISSUE TITLE
Porting electron-api-demos to Electron Fiddle examples in docs

### ISSUE THREAD

**Issue by erickzhao** [electron/electron#20442]
## Context

This meta-issue addresses a need to bridge the gap between our website's online docs, `electron-api-demos`, and Electron Fiddle.

- <details><summary>What's <code>electron-api-demos</code>?</summary>
   <p>
   As the name indicates, <code>electron-api-demos`</code> is a collection of examples for Electron APIs wrapped in an application. Each demo contains a executable example of the API along with sample code and additional explanations.
    </p>
    </details>

- <details><summary>What's Electron Fiddle?</summary>
   <p>
   Electron Fiddle is a code playground allowing developers to tinker around with small experiments that can later be exported into full-fledged Electron applications. The interface allows users to create and run small Electron apps with a single <code>main.js</code>, <code>renderer.js</code>, and <code>index.html</code>.
   </p>
   </details>
- <details><summary>Motivation</summary>
   <ul>
   <li>Although collecting runnable API demos is nice, having the sample code gated behind an application increases friction, and maintaining the app in its current state for more than 1 release line is difficult.</li>
    <li> Having the code available online makes it easier to find and more accessible to read, but having to manually launch </li>
    <li> <strong>Porting over <code>electron-api-demos</code> into Fiddle-friendly examples is a big step into ultimately having API code samples available in the docs as runnable Fiddles.</strong> </li> </details>
- <details>
   <summary>Current Progress</summary>
   <ul><li>Recently, Electron Fiddle added the capability of loading code directly from the docs on the <code>electron/electron repo</code> (see electron/fiddle/pull/203). However, there are currently no examples!</li>
     <li>The ElectronJS website currently has an open PR (electron/electronjs.org/pull/2848]) adding the ability to launch the Fiddle protocol from the Electron website.</li>
</details>
   </ul>

## Task

We will be attempting to port over all of the `electron-api-demos` examples in the codebase. For context on how API demos are structured, see the docs [here](https://github.com/electron/electron-api-demos/blob/master/docs.md). 

The task is to ultimately convert each demo into an Electron Fiddle sample that's equivalent in functionality. **Please include the explanatory text from the HTML files as well.** Note that many of these demos are tightly coupled in logic, and a single PR can be submitted for multiple demos within a Section.

The easiest way to do so is to pick an example in `electron-api-demos`, recreate the example in Electron Fiddle (using the `electron-api-demo` source code as a starting point), save the Fiddle locally into a folder, and move that example into `/docs/fiddles/[CATEGORY]/[SECTION]/[DEMO]`.

### Example Fiddle

See the following PR for an example of this task (Asynchronous Messages demo): #20441 

### Code style

Code should follow the StandardJS style guidelines. To format your code, run the following snippet in your directory.

```shell
    npm install -g standard # if you don't have it installed
    cd YOUR_FIDDLE_IN_DOCS_FOLDER
    standard --fix
```

### Folder structure

Add the contents of your Fiddle (`main.js`, `renderer.js` , and `index.html` but **not** `package.json`) into a new `/docs/fiddles/[CATEGORY]/[SECTION]/[DEMO]` folder in your fork of `electron/electron`

For a handy graph on what category/section/demo mean:

![](https://raw.githubusercontent.com/electron/electron-api-demos/master/assets/img/ui-terminology.png)

## PR requirements

- PR is merging into `master` branch.
- File structure adheres to the requirements above.
- Code in PR runs successfully in Electron Fiddle with the latest release of **Electron 6**.
- Code in PR passes a linting check with Standard.

## Assignees

**Since this is a meta-issue that will require many PRs from contributors, we will attempt to proceed in a first-come-first-serve fashion. Examples will be marked as claimed as soon as a PR is opened for them.**

**In the interest of focusing on getting each PR reviewed and merged, please only open one PR at a time before opening another.**

## List of Demos

- [ ]  Windows
    - [x]  Create and manage windows
        - [x]  ~Create a new window  @wedob13 #20480~
        - [x]  Manage window state
        - [x]  Window events (blur and focus)
        - [x]  ~Create a frameless window @kristofkalocsai #20591~
    - [ ]  Handling window crashes and hangs
        - [x]  Relaunch window after the process crashes @ValerianClerc #20571
        - [ ]  Relaunch window after the process hangs
- [x]  Menus
    - [x]  ~Customize menus @yashints #20468~
        - [x]  ~Create an application menu~
        - [x]  ~Create a context menu~
    - [x]  ~Keyboard shortcuts~
        - [x]  ~Register a global keyboard shortcut @yashints #20466~
- [ ]  Native User Interface
    - [x]  Open external links and the file manager
        - [x]  ~Open path in file manager @kristofkalocsai #20589~
        - [x]  ~Open external links @alanionita #20763~
    - [x] ~Desktop notifications  @harryi3t #20528~
        - [x] ~Basic notification~
        - [x] ~Notification with image~
    - [x]  ~Use system dialogs @yashints #20473~
        - [x] ~Open a file or directory~
        - [x]  ~Error dialog~
        - [x]  ~Information dialog~
        - [x] ~Save dialog~
    - [ ]  Tray
        - [ ]  Tray
    - [x]  ~Drag and drop files~
        - [x]  ~Dragging files @yashints #20472~
- [ ]  Communication
    - [ ]  Communicate between processes
        - [x]  ~Asynchronous messages @erickzhao #20441~
        - [x]  ~Synchronous messages  @97amarnathk #20451~
        - [ ]  Communicate with an invisible window
- [ ]  System
    - [ ]  Get app or user system information
        - [x]  ~Get app information @97amarnathk #20487~
        - [x]  ~Get version information @RikTheunis #20536~
        - [x]  ~Get system information @jh3y #20662~
        - [ ]  Get screen information
    - [x]  ~Clipboard @RikTheunis #20445~
        - [x]  ~Copy~
        - [x]  ~Paste~
    - [x]  Protocol Handler
        - [x]  ~Launch app from URL in another app @alanionita #20718~
- [x]  Media
    - [x]  Take screenshot
        - [x]  ~Take a screenshot @harryi3t #20531~
---

**Comment by 97amarnathk** [comment]
I would like to work on this. Can this be assigned to me?

**Comment by erickzhao** [comment]
> I would like to work on this. Can this be assigned to me?

@97amarnathk Feel free to submit a PR for any demo (see #20441 for an example). I'll keep the meta-issue with assignees as the PRs flow in.

**Comment by 97amarnathk** [comment]
@erickzhao Where do I find the HTML files related to synchronous communication?

**Comment by erickzhao** [comment]
> @erickzhao Where do I find the HTML files related to synchronous communication?

@97amarnathk You can find all relevant HTML files included in the [`sections`](https://github.com/electron/electron-api-demos/tree/master/sections) folder of `electron-api-demos`. For the case of synchronous communications, find the file under `sections/communications/ipc.html`.

For more info on how `electron-api-demos` is structured, see this design doc: https://github.com/electron/electron-api-demos/blob/master/docs.md

**Comment by 97amarnathk** [comment]
https://github.com/electron/electron/pull/20451

**Comment by 97amarnathk** [comment]
@erickzhao I have submitted https://github.com/electron/electron/pull/20451 for Synchronous Messages.

**Comment by yashints** [comment]
Hey @erickzhao, had a question for you. I am working on adding the manage window section in which the renderer is referencing a local html file by path (modal.html). I can't add additional files to Fiddle to be referenced. What's the workaround?

**Comment by wedob13** [comment]
@erickzhao I have submitted #20480 for 'Create a new Window' i can grab another one as soon as this pull gets merged.

Thanks for checking it out :)

**Comment by 97amarnathk** [comment]
@erickzhao I added a PR for getting app info.
https://github.com/electron/electron/pull/20487

**Comment by harryi3t** [comment]
@ericbrumer Raised PR for context menu
https://github.com/electron/electron/pull/20506

Also, didn't find any demo button for `application menu`, it's just static code. Wanted to cover that too in the same PR  🙂
![image](https://user-images.githubusercontent.com/5207331/66510790-5d9c7d00-eaf3-11e9-8862-e4a9a36e5347.png)

**Comment by yashints** [comment]
> @ericbrumer Raised PR for context menu 
> #20506
> 
> Also, didn't find any `view demo` button for `application menu`, it's just static code. Wanted to cover that too in the same PR 🙂
> ![image](https://user-images.githubusercontent.com/5207331/66510790-5d9c7d00-eaf3-11e9-8862-e4a9a36e5347.png)

Hmmm 👉🏼https://github.com/electron/electron/pull/20468

**Comment by harryi3t** [comment]
Hey @yashints,
Sorry didn't see that there was already a PR. The description said that the items would be checked off when someone raises a PR for them

> Examples will be marked as claimed as soon as a PR is opened for them.

I will close my PR and I guess I would have to go through all the linked PRs to get an idea of what's already taken.

**Comment by erickzhao** [comment]
Sorry for the confusion, will update the list ASAP and get to reviewing some PRs today :)

**Comment by 97amarnathk** [comment]
@erickzhao , I provided a PR for app information and not clipboard. Could you update the Issue description accordingly?

**Comment by yashints** [comment]
@erickzhao I need to find out how to include assets (icons, templates, etc) in Fiddle examples, any hints?

**Comment by erickzhao** [comment]
>  I need to find out how to include assets (icons, templates, etc) in Fiddle examples, any hints?
@yashints Previous patterns simply generated the image from the Data URL

See: https://github.com/electron/fiddle/blob/master/static/show-me/tray/main.js

**Comment by yashints** [comment]
Thanks, what about html templates? like modals

**Comment by erickzhao** [comment]
@yashints I talked about this a bit in the Create Window issue, but as a solution, loading an external URL (e.g. `https://electronjs.org`) could be a standby for loading an HTML partial.

**Comment by yashints** [comment]
NP, I will create my PR with an external link then

**Comment by wedob13** [comment]
@erickzhao is it okay if i get started on another pull or should i wait for my previous one to be reviewed?

**Comment by erickzhao** [comment]
@wedob13 I'd say to go for it! I've been lagging behind on reviewing the PRs lately.

**Comment by erickzhao** [comment]
This is pretty much done in 2022 :)
