### ISSUE TITLE
new BrowserWindow with property "transparent:true" can cause crash

### ISSUE THREAD

**Issue by 420577898** [electron/electron#24705]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  9.1.0
* **Operating System:**
  win7 64
* **Last Known Working Electron version:**
  8.3.1

### Expected Behavior

  offScreenWin = new BrowserWindow({
      height: 1080,
      useContentSize: true,
      webPreferences: {
        offscreen: true,
        webSecurity:false,
        nodeIntegration: true
      },
      show:false,
      transparent:true,
      frame:false,
      width: 1920
    });
### Actual Behavior

work well
### To Reproduce

just npm run dev     to start

**Comment by RomanLubushkin** [comment]
Hey guys, any news or workarounds on this bug?
Blocks us to update to the latest Electron version which is recommended by Electron security policy

**Comment by PieterVanZyl-NWU** [comment]
I would like to confirm that this breaks for me too

I was running Electron 10.0.0

And electron would crash when declaring a BrowserWindow with 
offscreen: true,
show:false,
transparent:true

Changing electron versions instantly fixed the problem 

Currently 8.3.1 Works.

I have resorted to downgrading as I don't even get error messages logs or info on the crash even if I put it in a try catch block.

**Comment by melody5417** [comment]
Got same problem, any news?

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by nornagon** [comment]
Additionally, this report is for a version of Electron that is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions). So the repro should show that the issue still occurs on a currently-supported version of Electron.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
