### ISSUE TITLE
Elements in transparent windows leave trail behind when resizing/dragging

### ISSUE THREAD

**Issue by septatrix** [electron/electron#26147]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** (tested with both)
  * v10.1.5
  * v12.0.0-nightly.20201023
* **Operating System:**
  * Ubuntu 20.04.1 LTS / x86_64
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Dragging and resizing an element inside a transparent windows should expose the previously occupied the space

### Actual Behavior
The element leaves a trail of copies behind

### To Reproduce

<details>
<summary>Code</summary>

`main.js`:
```js
// Modules to control application life and create native browser window
const { app, BrowserWindow } = require('electron')

function createWindow() {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    show: false,
    // width: 800,
    // height: 600,
    // frame: false,
    transparent: true,
    backgroundColor: '#00000000',
  })

  // mainWindow.maximize()
  // mainWindow.loadFile('index.html')
  mainWindow.loadFile('minimal.html')
  mainWindow.show()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') app.quit()
})

app.on('activate', function() {
  // On macOS it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) createWindow()
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```

`minimal.html`:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Draggable div</title>
</head>
<body>
    <textarea></textarea>
</body>
</html>

```

</details>

### Screenshots
https://webmshare.com/play/DBNqj

### Additional Information
* v10 behaves the same as v12-nightly for x11 without ozone
* running under wayland
* v12-nightly with ozone and wayland is the only one with proper transparency

**Comment by ckerr** [comment]
gist version of @septatrix's repro case: https://gist.github.com/ckerr/4e2b53da4dd6357045e46b7af2890f62

Reproducible here w/ Electron v10.1.5 on a stock Ubuntu 20.04 box:

![2020-10-25T12:36:09-Screenshot-820x655](https://user-images.githubusercontent.com/70381/97114570-452be000-16bf-11eb-935e-a7367e364bc1.png)

**Comment by septatrix** [comment]
Thank you for the gist. I also would like to add that this does not only happens with a `<textarea>` but also other elements. However this way requires no javascript and therefore removes a potential error source.

**Comment by septatrix** [comment]
Still present in 12.0.0

**Comment by shash7** [comment]
Any update on this? This is kind of a deal breaker for my app.

**Comment by shash7** [comment]
Nvm I figured out a fix. Turns out, when you set `hasShadow` to false when creating a window, that outline/shadow/stroke/trail dissapears.

Here's where I found this fix:
https://stackoverflow.com/questions/60507653/electronjs-no-shadoow-when-window-is-transparent

**Comment by septatrix** [comment]
I ran the same code with electron 15 and it worked as expected for X11 and Ozone/X11 however it did not start under Ozone/Wayland. While `hasShadow: true` did not work in my case, `frame: false` did and is satisfactory for me. As Ozone/Wayland is presumably still in a beta stage I will close this as it is now resolved for my use case.
