### ISSUE TITLE
[Bug]: transparent windows not working with allowRendererProcessReuse: false in 11.4.1

### ISSUE THREAD

**Issue by cholic1025** [electron/electron#28475]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.1

### What operating system are you using?

macOS

### Operating System Version

10.14.6

### What arch are you using?

x64

### Last Known Working Electron version

11.3.0

### Expected Behavior

The window should be transparent

### Actual Behavior

When electron is updated to 11.4.1 and app.allowRendererProcessReuse setting with False, transparent windows are not working any more.
It works fine in electron 11.3.0 or set allowRendererProcessReuse with True.

### Testcase Gist URL

https://gist.github.com/cholic1025/649bcb7cab7a5fe7542c027939a31d3c

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by cholic1025** [comment]
> gist

https://gist.github.com/649bcb7cab7a5fe7542c027939a31d3c

**Comment by cholic1025** [comment]
@nornagon I just updated the gist URL in description, is this enough to test?

**Comment by nornagon** [comment]
@cholic1025 yep, that's great. Confirmed the issue and bisected to https://github.com/electron/electron/compare/v11.3.0...v11.4.0. https://github.com/electron/electron/pull/28186 and https://github.com/electron/electron/pull/27944 look related. cc @codebytere @MarshallOfSound @marekharanczyk

**Comment by MarshallOfSound** [comment]
Is it working on the latest nightly?

https://github.com/electron/electron/pull/28054 might have fixed it

**Comment by nornagon** [comment]
@MarshallOfSound it's working in the current nightly, but it looks like it was fixed in the range https://github.com/electron/electron/compare/v14.0.0-nightly.20210304...v14.0.0-nightly.20210305

**Comment by cholic1025** [comment]
@nornagon any update on this?

**Comment by yaohy0819** [comment]
I have test, maybe is this change caused the bug.
https://github.com/electron/electron/commit/87064e5b5e19b9165beff5483a1953e07245d66b#diff-261075c0abf5bfd33be70313bcd3699da9b1222b6f27df0e8294fc63789f160b

**Comment by Serena-zlh** [comment]
@nornagon 

> @MarshallOfSound it's working in the current nightly, but it looks like it was fixed in the range [v14.0.0-nightly.20210304...v14.0.0-nightly.20210305](https://github.com/electron/electron/compare/v14.0.0-nightly.20210304...v14.0.0-nightly.20210305)

Can we fix this on version 11?

**Comment by nornagon** [comment]
I'm closing this as wontfix because 11.x is now only receiving security updates, and this is working correctly on the latest versions of 12.x and 13.x (12.0.9 and 13.0.1 at the time of writing).
