### ISSUE TITLE
[Bug]: Transparent Background Doesn't Work in Windows when I use setSize()

### ISSUE THREAD

**Issue by RavinRau** [electron/electron#29661]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.2

### What operating system are you using?

Windows

### Operating System Version

20H2

### What arch are you using?

x64

### Last Known Working Electron version

9.2.0

### Expected Behavior

The background should appear transparent after multiple setSize()

### Actual Behavior

![image (2)](https://user-images.githubusercontent.com/12477629/121814415-9404a500-cca3-11eb-8612-1a590a3a4981.png)

When I upgrade to the latest electron I am getting this problem where the background is black in color. Back when I am using version 9.2.0 it works perfectly fine. 

How to recreate this issue
The problem occurs when I am trying to resize my BrowserWindow by using setSize(). 
1. At the initial launch, the transparent works fine with a small.
2. When resized to a bigger size using setSize() and back to the small size the background becomes black.

I have tried other ways like setBounds but still, it doesn't work as expected.

### Additional Information

The problem also occurs in version 10.4.7

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.

**Comment by Juniourrau** [comment]
@codebytere I am trying to create an Electron Fiddle test case for you to test out, but I am facing an issue with the electron fiddle. 

I link an issue 3 days ago here https://github.com/electron/fiddle/issues/699#issuecomment-862491261 but there wasn't any reply. It would be great if you are able to check and reply to that issue. As it is kinda blocking me to produce the bug for this issue.

**Comment by qkrooz** [comment]
You need to set frame:false to your BrowserWindow configuration.
