### ISSUE TITLE
[Bug]: ESM cannot be used with contextIsolation: false import.meta.url

### ISSUE THREAD

**Issue by Lingyan000** [electron/electron#40989]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.1.3

### What operating system are you using?

Windows

### Operating System Version

22631.3007

### What arch are you using?

x64

### Last Known Working Electron version

28.1.3

### Expected Behavior

The rendering process renders normally.

### Actual Behavior

In ESM, `import.meta.url` is not available in `preload` when I use `contextIsolation: false`,rendering process is unresponsive.

### Testcase Gist URL

https://gist.github.com/f9cde94e621204933822255591f11011

**Comment by codebytere** [comment]
@MarshallOfSound do you know if this is expected per our implementation?

**Comment by MarshallOfSound** [comment]
Haven't run the code so not exactly sure what happens, but this doesn't sound like a known limitation.  Cautiously I'd call it a bug

**Comment by codebytere** [comment]
Confirmed - looks like it DCHECKs on local builds:

<details><summary>Stacktrace</summary>
<p>

```
[87995:0115/131548.063150:FATAL:module_record_resolver_impl.cc(53)] Check failed: it != record_to_module_script_map_.end() (iterator representing <end> vs. iterator representing <end>)Failed to find ModuleScript corresponding to the record.[[HostDefined]]
0   Electron Framework                  0x000000011fa53ec4 base::debug::CollectStackTrace(void const**, unsigned long) + 28
1   Electron Framework                  0x000000011fa435b8 base::debug::StackTrace::StackTrace() + 24
2   Electron Framework                  0x000000011f96ed38 logging::LogMessage::~LogMessage() + 160
3   Electron Framework                  0x000000011f957e28 logging::(anonymous namespace)::CheckLogMessage::~CheckLogMessage() + 292
4   Electron Framework                  0x000000011f957ef0 logging::(anonymous namespace)::CheckLogMessage::~CheckLogMessage() + 12
5   Electron Framework                  0x000000011f957b54 logging::CheckError::~CheckError() + 40
6   Electron Framework                  0x000000011f957b84 logging::CheckError::~CheckError() + 12
7   Electron Framework                  0x0000000122781b8c blink::ModuleRecordResolverImpl::GetModuleScriptFromModuleRecord(v8::Local<v8::Module>) const + 368
8   Electron Framework                  0x000000012277a9fc blink::ModulatorImplBase::HostGetImportMetaProperties(v8::Local<v8::Module>) const + 48
9   Electron Framework                  0x000000012188aed8 blink::V8Initializer::HostGetImportMetaProperties(v8::Local<v8::Context>, v8::Local<v8::Module>, v8::Local<v8::Object>) + 112
10  Electron Framework                  0x000000011c4c1b84 v8::internal::Isolate::RunHostInitializeImportMetaObjectCallback(v8::internal::Handle<v8::internal::SourceTextModule>) + 372
11  Electron Framework                  0x000000011ca2cf64 v8::internal::SourceTextModule::GetImportMeta(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SourceTextModule>) + 120
12  Electron Framework                  0x000000011cbc41cc v8::internal::__RT_impl_Runtime_GetImportMetaObject(v8::internal::Arguments<(v8::internal::ArgumentsType)0>, v8::internal::Isolate*) + 92
13  Electron Framework                  0x000000011cbc3dd4 v8::internal::Runtime_GetImportMetaObject(int, unsigned long*, v8::internal::Isolate*) + 140
14  ???                                 0x0000000157e7c0f4 0x0 + 5769773300
15  ???                                 0x0000000157fba9c0 0x0 + 5771078080
16  ???                                 0x0000000157dd14dc 0x0 + 5769073884
17  ???                                 0x0000000157e180a8 0x0 + 5769363624
18  ???                                 0x0000000157dce6a8 0x0 + 5769062056
19  ???                                 0x0000000157dce398 0x0 + 5769061272
20  Electron Framework                  0x000000011c482e1c v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) + 2744
21  Electron Framework                  0x000000011c48469c v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) + 156
22  Electron Framework                  0x000000011c484b98 v8::internal::Execution::TryCall(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*, v8::internal::Execution::MessageHandling, v8::internal::MaybeHandle<v8::internal::Object>*) + 320
23  Electron Framework                  0x000000011ca2f2e0 v8::internal::SourceTextModule::ExecuteModule(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SourceTextModule>, v8::internal::MaybeHandle<v8::internal::Object>*) + 300
24  Electron Framework                  0x000000011ca2ddc4 v8::internal::SourceTextModule::InnerModuleEvaluation(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SourceTextModule>, v8::internal::ZoneForwardList<v8::internal::Handle<v8::internal::SourceTextModule>>*, unsigned int*) + 1400
25  Electron Framework                  0x000000011ca2d564 v8::internal::SourceTextModule::Evaluate(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SourceTextModule>) + 240
26  Electron Framework                  0x000000011c9a0d38 v8::internal::Module::Evaluate(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Module>) + 708
27  Electron Framework                  0x000000011c185eb8 v8::Module::Evaluate(v8::Local<v8::Context>) + 992
28  Electron Framework                  0x000000012484221c node::loader::ModuleWrap::Evaluate(v8::FunctionCallbackInfo<v8::Value> const&) + 1196
29  ???                                 0x0000000157dd3da4 0x0 + 5769084324
30  ???                                 0x0000000157dd14dc 0x0 + 5769073884
31  ???                                 0x0000000157e15cdc 0x0 + 5769354460
32  ???                                 0x0000000157f1f168 0x0 + 5770441064
33  ???                                 0x0000000157e029ac 0x0 + 5769275820
34  ???                                 0x0000000157dce598 0x0 + 5769061784
35  Electron Framework                  0x000000011c482e74 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) + 2832
36  Electron Framework                  0x000000011c48469c v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) + 156
37  Electron Framework                  0x000000011c484d18 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*) + 108
38  Electron Framework                  0x000000011c4d6a0c v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) + 608
39  Electron Framework                  0x000000011c4d674c v8::internal::MicrotaskQueue::PerformCheckpointInternal(v8::Isolate*) + 116
40  Electron Framework                  0x00000001247f5390 node::InternalCallbackScope::Close() + 248
41  Electron Framework                  0x00000001247f5094 node::InternalCallbackScope::~InternalCallbackScope() + 20
42  Electron Framework                  0x00000001248ad8cc node::fs::FileHandle::CloseReq::Resolve() + 212
43  Electron Framework                  0x00000001248c7794 _ZZN4node2fs10FileHandle12ClosePromiseEvEN3$_08__invokeEP7uv_fs_s + 476
44  Electron Framework                  0x00000001248a2758 node::MakeLibuvRequestCallback<uv_fs_s, void (*)(uv_fs_s*)>::Wrapper(uv_fs_s*) + 116
45  Electron Framework                  0x000000011a8a6188 uv__work_done + 184
46  Electron Framework                  0x000000011a8a9878 uv__async_io + 280
47  Electron Framework                  0x000000011a8ba6ac uv__io_poll + 1716
48  Electron Framework                  0x000000011a8a9d70 uv_run + 412
49  Electron Framework                  0x000000011aacea98 electron::NodeBindings::UvRunOnce() + 228
50  Electron Framework                  0x000000011a9009ec base::internal::Invoker<base::internal::BindState<void (net::(anonymous namespace)::DnsHTTPAttempt::*)(), base::WeakPtr<net::(anonymous namespace)::DnsHTTPAttempt>>, void ()>::RunOnce(base::internal::BindStateBase*) + 88
51  Electron Framework                  0x000000011a8c26e0 base::OnceCallback<void ()>::Run() && + 68
52  Electron Framework                  0x000000011f9c5f9c base::TaskAnnotator::RunTaskImpl(base::PendingTask&) + 272
53  Electron Framework                  0x000000011f9f5b34 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) + 1392
54  Electron Framework                  0x000000011f9f526c base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() + 104
55  Electron Framework                  0x000000011f976fc8 base::MessagePumpDefault::Run(base::MessagePump::Delegate*) + 152
56  Electron Framework                  0x000000011f9f69b0 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) + 688
57  Electron Framework                  0x000000011f9a6958 base::RunLoop::Run(base::Location const&) + 592
58  Electron Framework                  0x000000012445f0f4 content::RendererMain(content::MainF
unctionParams) + 1620
59  Electron Framework                  0x000000011aca8644 content::RunOtherNamedProcessTypeMain(std::__Cr::basic_string<char, std::__Cr::char_traits<char>, std::__Cr::allocator<char>> const&, content::MainFunctionParams, content::ContentMainDelegate*) + 696
60  Electron Framework                  0x000000011aca9fa8 content::ContentMainRunnerImpl::Run() + 1140
61  Electron Framework                  0x000000011aca796c content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) + 1216
62  Electron Framework                  0x000000011aca7bb0 content::ContentMain(content::ContentMainParams) + 100
63  Electron Framework                  0x000000011a8bac88 ElectronMain + 128
64  Electron Helper (Renderer)          0x0000000102894a5c main + 220
65  dyld                                0x000000018263d0e0 start + 2360
Task trace:
0   Electron Framework                  0x000000011aaced24 electron::NodeBindings::WakeupMainThread() + 72
Crash keys:
  "renderer_foreground" = "true"
  "v8_ro_space_firstpage_address" = "0x317f00000000"
  "v8_isolate_address" = "0x10001060000"
  "num-experiments" = "0"
  "platform" = "darwin"
  "process_type" = "renderer"
  "osarch" = "arm64"
  "pid" = "87995"
  "ptype" = "renderer"
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
```

</p>
</details>
