### ISSUE TITLE
[Feature Request]: Event: 'did-change-theme-color'支持全量的css color (主要支持透明度),不解析也行,直接callback meta content

### ISSUE THREAD

**Issue by code-small-white** [electron/electron#41954]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

现在只支持 主题颜色格式为 '#rrggbb'
**我需要透明度**

### Proposed Solution

<meta name='theme-color' content='#ffffff'>
....rgba(0,0,0,0)
...transparent
callback 里面可以直接返回content内容,不解析,或者把解析后的,和解析前的都返回

### Alternatives Considered

无
